// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkgjY5FftvLlAPV9fjfb2MdnCoy3tsUM',
    appId: '1:113483233361:android:77ef7667913e98436fa070',
    messagingSenderId: '113483233361',
    projectId: 'library-application-c643e',
    storageBucket: 'library-application-c643e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKR6jK3W7iHqXZhGHQoM5RXzXFj5NdRQI',
    appId: '1:113483233361:web:3ac7ed2e3461a3016fa070',
    messagingSenderId: '113483233361',
    projectId: 'library-application-c643e',
    authDomain: 'library-application-c643e.firebaseapp.com',
    storageBucket: 'library-application-c643e.firebasestorage.app',
    measurementId: 'G-M647MVF2Y7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4L8m1Y0HzFH1kgKKtfEma2S7uXRRuaM',
    appId: '1:113483233361:ios:ecb79bf9ae2dab096fa070',
    messagingSenderId: '113483233361',
    projectId: 'library-application-c643e',
    storageBucket: 'library-application-c643e.firebasestorage.app',
    iosBundleId: 'com.mycompany.libraryapplication',
  );

}